export default {
    SERVER_URL: 'https://server.reezx.com/api',
    PATHS: {
        getBloodBanks: '/bloodbanks',
        getDonors: '/bb/donors',
        addMotivator: '/admin/motivators',
        getMotivators: '/bb/motivators',
        getPostoffice: '/bb/areas/postoffices',
        getAreas: '/bb/areas/',
        getPincodeDetails: '/bb/areas/pincode/',
        getTotalDonors: '/bb/donors/count',
        getAnalytics: '/bb/analytics',
        addDonor: '/bb/donors/new',
        updateDonor: '/bb/donors/',
        getSerums: '/bb/pus/serums',
        addSerums: '/bb/pus/serums/add',
        useSerums: '/bb/pus/serums/use',
        getKits: '/bb/pus/kits',
        addKits: '/bb/pus/kits/add',
        useKits: '/bb/pus/kits/use',
        getChemicals: '/bb/pus/chemicals',
        addChemicals: '/bb/pus/chemicals/add',
        useChemicals: '/bb/pus/chemicals/use',
        getBloodBags: '/bb/pus/bloodbags',
        addBloodBags: '/bb/pus/bloodbags/add',
        useBloodBags: '/bb/pus/bloodbags/use',
        inputBlood: '/bb/input/blood',
        inputStock: '/bb/input/stock',
        inputScreening: '/bb/input/screening',
        inputDiscard: '/bb/input/discard',
        inputGrouping: '/bb/input/grouping',
        inputInfectious: '/bb/input/infectious',
        inputPreparation: '/bb/input/preparation',
        inputReject: '/bb/input/reject',
        outputBlood: '/bb/output/blood',
        outputBMR: '/bb/output/bmr',
        outputCM: '/bb/output/matching',
        outputPG: '/bb/output/grouping',
        outputPreservation: '/bb/output/preservation'
    },
    AUTH: {
        username: 'Haemcare - Nungambakkam',
        password: 'password',
        token: 'cdc04a76-8945-4014-867f-d333cd24e847'
    }
}